version: '3.8'

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0' -p 3000"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      WEBPACKER_DEV_SERVER_HOST: "webpacker"
    depends_on:
      - webpacker

  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app
    ports:
      - "3035:3035"
    environment:
      NODE_ENV: development
